spring.application.name=MatchBeauty

# Configura\u00e7\u00f5es do Banco de Dados
spring.datasource.url=jdbc:mysql://localhost:3307/beautymatch?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configura\u00e7\u00f5es do JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Configura\u00e7\u00f5es do BCrypt
spring.security.crypto.bcrypt.BCryptPasswordEncoder=10

# Configura\u00e7\u00f5es do SQL
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# Configura\u00e7\u00f5es do JWT
app.jwt.secret=beautyMatchSecretKey2024
app.jwt.expiration=900000
